In [1]:
import pandas as pd

fish = pd.read_csv('https://bit.ly/fish_csv_data')
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [2]:
fish.to_csv('fish.csv')

In [3]:
fish.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Species   159 non-null    object 
 1   Weight    159 non-null    float64
 2   Length    159 non-null    float64
 3   Diagonal  159 non-null    float64
 4   Height    159 non-null    float64
 5   Width     159 non-null    float64
dtypes: float64(5), object(1)
memory usage: 7.6+ KB


In [4]:
fish.describe()

Weight      Length    Diagonal      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   28.415723   31.227044    8.970994    4.417486
std     357.978317   10.716328   11.610246    4.286208    1.685804
min       0.000000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   63.400000   68.000000   18.957000    8.142000

In [5]:
fish.isna().sum()

Species     0
Weight      0
Length      0
Diagonal    0
Height      0
Width       0
dtype: int64

In [6]:
fish.columns

Index(['Species', 'Weight', 'Length', 'Diagonal', 'Height', 'Width'], dtype='object')

In [ ]:
# Bream 도미, Roach 잉어과 Whitefish 송어,   Parkki 청돔, Perch 농어,Pike 강꼬치고기, Smelt 빙어

In [8]:
fish['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [9]:
fish['Species'].value_counts()

Species
Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: count, dtype: int64

In [11]:
fish[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].values

array([[2.42000e+02, 2.54000e+01, 3.00000e+01, 1.15200e+01, 4.02000e+00],
       [2.90000e+02, 2.63000e+01, 3.12000e+01, 1.24800e+01, 4.30560e+00],
       [3.40000e+02, 2.65000e+01, 3.11000e+01, 1.23778e+01, 4.69610e+00],
       [3.63000e+02, 2.90000e+01, 3.35000e+01, 1.27300e+01, 4.45550e+00],
       [4.30000e+02, 2.90000e+01, 3.40000e+01, 1.24440e+01, 5.13400e+00],
       [4.50000e+02, 2.97000e+01, 3.47000e+01, 1.36024e+01, 4.92740e+00],
       [5.00000e+02, 2.97000e+01, 3.45000e+01, 1.41795e+01, 5.27850e+00],
       [3.90000e+02, 3.00000e+01, 3.50000e+01, 1.26700e+01, 4.69000e+00],
       [4.50000e+02, 3.00000e+01, 3.51000e+01, 1.40049e+01, 4.84380e+00],
       [5.00000e+02, 3.07000e+01, 3.62000e+01, 1.42266e+01, 4.95940e+00],
       [4.75000e+02, 3.10000e+01, 3.62000e+01, 1.42628e+01, 5.10420e+00],
       [5.00000e+02, 3.10000e+01, 3.62000e+01, 1.43714e+01, 4.81460e+00],
       [5.00000e+02, 3.15000e+01, 3.64000e+01, 1.37592e+01, 4.36800e+00],
       [3.40000e+02, 3.20000e+01, 3.73

In [12]:
import numpy as np
import pandas as pd
# 옵션 설정: 모든 float 열을 소수점 2자리로 표시
pd.set_option('display.float_format', '{:.2f}'.format)

# 지수 표기법 억제하고 소수점 2자리로 고정
np.set_printoptions(suppress=True,    # 지수 표기법(e) 안 쓰기
                    precision=2,      # 소수점 아래 2자리
                    floatmode='fixed')  # 항상 소수점 2자리 표시 (0도 채움)

In [13]:
fish[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].values

array([[ 242.00,   25.40,   30.00,   11.52,    4.02],
       [ 290.00,   26.30,   31.20,   12.48,    4.31],
       [ 340.00,   26.50,   31.10,   12.38,    4.70],
       [ 363.00,   29.00,   33.50,   12.73,    4.46],
       [ 430.00,   29.00,   34.00,   12.44,    5.13],
       [ 450.00,   29.70,   34.70,   13.60,    4.93],
       [ 500.00,   29.70,   34.50,   14.18,    5.28],
       [ 390.00,   30.00,   35.00,   12.67,    4.69],
       [ 450.00,   30.00,   35.10,   14.00,    4.84],
       [ 500.00,   30.70,   36.20,   14.23,    4.96],
       [ 475.00,   31.00,   36.20,   14.26,    5.10],
       [ 500.00,   31.00,   36.20,   14.37,    4.81],
       [ 500.00,   31.50,   36.40,   13.76,    4.37],
       [ 340.00,   32.00,   37.30,   13.91,    5.07],
       [ 600.00,   32.00,   37.20,   14.95,    5.17],
       [ 600.00,   32.00,   37.20,   15.44,    5.58],
       [ 700.00,   33.00,   38.30,   14.86,    5.29],
       [ 700.00,   33.00,   38.50,   14.94,    5.20],
       [ 610.00,   33.50,   

In [14]:
X=fish[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].values

In [15]:
y=fish['Species'].values

In [16]:
y

array(['Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Whitefish',
       'Whitefish', 'Whitefish', 'Whitefish', 'Whitefish', 'Whitefish',
       'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki',
       'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perc

In [17]:
X.shape

(159, 5)

In [18]:
y.shape

(159,)

In [19]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
    X, y, random_state=42)

In [21]:
train_input[:5]

array([[720.00,  35.00,  40.60,  16.36,   6.09],
       [500.00,  45.00,  48.00,   6.96,   4.90],
       [  7.50,  10.50,  11.60,   1.97,   1.16],
       [110.00,  22.00,  23.50,   5.52,   4.00],
       [140.00,  20.70,  23.20,   8.54,   3.29]])

In [22]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
# ss.fit(train_input)
train_scaled = ss.fit_transform(train_input)
test_scaled = ss.fit_transform(test_input)

In [23]:
train_scaled[:5]

array([[ 0.92,  0.61,  0.81,  1.85,  1.00],
       [ 0.30,  1.55,  1.45, -0.47,  0.27],
       [-1.09, -1.69, -1.71, -1.70, -2.00],
       [-0.80, -0.61, -0.67, -0.82, -0.28],
       [-0.71, -0.73, -0.70, -0.08, -0.70]])

In [24]:
test_scaled[:5]

array([[-0.93, -0.88, -1.00, -0.84, -0.67],
       [-1.11, -1.47, -1.50, -1.41, -1.71],
       [-0.59,  0.39,  0.31, -0.77, -0.53],
       [-0.40, -0.20, -0.20, -0.19, -0.04],
       [-0.73, -0.48, -0.56, -0.84, -0.39]])

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
kn = KNeighborsClassifier(n_neighbors=3)

In [27]:
kn.fit(train_scaled, train_target)

KNeighborsClassifier(n_neighbors=3)

In [28]:
# 학습데이터 성능
# 테스트데이터 성능

In [29]:
print(kn.score(train_scaled, train_target))
print(kn.score(test_scaled, test_target))

0.8907563025210085
0.875
